[tool.poetry]
name = "mefmetrbot"
version = "1.3.3"
description = ""
authors = ["clownless <cuwuless@gmail.com>", "m4d3 <lirin@antrs.media>"]
license = "GPL-3.0"
readme = "README.md"
repository = "https://github.com/clownless/MefMetrBot"

[tool.poetry.dependencies]
python = "^3.10"
aiogram = "^2.25.1"
python-dotenv = "^0.21.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
